# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-02 01:51
from __future__ import unicode_literals

import datetime
import uuid

import Coms.models
import django.contrib.postgres.fields.jsonb
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.contrib.auth.models import Group, Permission
from django.contrib.contenttypes.models import ContentType
from django.db import migrations, models
from django.utils.timezone import utc


# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# Coms.migrations.0013_create_permissions


def create_groups(apps, schema_editor):
    new_group = Group.objects.get_or_create(name="Commissioners")[0]
    add_commission = Permission.objects.get(codename="add_commission")
    new_group.permissions.add(add_commission)

    new_group.permissions.add(add_commission)
    view_commission = Permission.objects.get(codename="view_commission")
    new_group.permissions.add(view_commission)
    change_commission = Permission.objects.get(codename="change_commission")
    new_group.permissions.add(change_commission)


class Migration(migrations.Migration):
    replaces = [(b'Coms', '0001_initial'), (b'Coms', '0013_create_permissions'), (b'Coms', '0002_auto_20160319_0418'),
                (b'Coms', '0003_auto_20160319_0519'), (b'Coms', '0004_auto_20160319_0526'),
                (b'Coms', '0005_auto_20160319_0600'), (b'Coms', '0006_auto_20160319_2157'),
                (b'Coms', '0007_auto_20160319_2159'), (b'Coms', '0008_auto_20160410_0205'),
                (b'Coms', '0009_auto_20160919_2308'), (b'Coms', '0010_auto_20160919_2334'),
                (b'Coms', '0011_commissionfiles_message'), (b'Coms', '0012_auto_20160920_0207'),
                (b'Coms', '0014_merge')]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name=b'Submitted')),
                ('locked', models.BooleanField(default=False)),
                ('status', models.IntegerField(
                    choices=[(0, b'Waiting'), (1, b'Sketched'), (2, b'Lined'), (3, b'Coloured'), (4, b'Finished'),
                             (5, b'Canceled'), (6, b'Please Revise'), (7, b'Rejected')], default=0)),
                ('paid', models.IntegerField(
                    choices=[(0, b'Not Yet Requested'), (1, b'Invoiced'), (2, b'Paid'), (3, b'Refunded')], default=0)),
                (
                'characters', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('description', models.TextField(blank=True, default=b'', max_length=10000)),
                ('details_date', models.DateTimeField(auto_now=True, verbose_name=b'Details Submitted')),
                ('submitted', models.BooleanField(default=False)),
                ('contacts', django.contrib.postgres.fields.jsonb.JSONField(default=list)),
                ('paypal', models.EmailField(blank=True, default=b'', max_length=254)),
            ],
            options={
                'default_permissions': ('add', 'view'),
            },
        ),
        migrations.CreateModel(
            name='CommissionFiles',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True, default=b'', max_length=1000)),
                ('imgname', models.CharField(max_length=1000)),
                ('img', models.ImageField(upload_to=Coms.models.file_name)),
                ('user_deleted', models.BooleanField(default=False)),
                ('deleted', models.BooleanField(default=False)),
                ('commission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Coms.Commission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ContactMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('message_url', models.URLField(blank=True)),
                ('profile_url', models.URLField(blank=True)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('disabled', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Contact Method',
            },
        ),
        migrations.CreateModel(
            name='Extra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('extra_character_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('disabled', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Commission Extra',
            },
        ),
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name=b'date created')),
                ('max_characters',
                 models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('character_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('max_commissions_in_queue', models.IntegerField(default=1)),
                ('max_commissions_per_person', models.IntegerField(default=1)),
                ('expire', models.IntegerField(default=15)),
                ('closed', models.BooleanField(default=False)),
                ('hidden', models.BooleanField(default=False)),
                ('end', models.DateTimeField(blank=True, default=None, null=True)),
                ('start', models.DateTimeField(default=django.utils.timezone.now)),
                ('extras', models.ManyToManyField(blank=True, to=b'Coms.Extra')),
            ],
            options={
                'verbose_name': 'Commission Queue',
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('extra_character_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('disabled', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Commission Size',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('extra_character_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('disabled', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Commission Type',
            },
        ),
        migrations.AddField(
            model_name='queue',
            name='sizes',
            field=models.ManyToManyField(to=b'Coms.Size'),
        ),
        migrations.AddField(
            model_name='queue',
            name='types',
            field=models.ManyToManyField(to=b'Coms.Type'),
        ),
        migrations.AddField(
            model_name='commission',
            name='extras',
            field=models.ManyToManyField(blank=True, to=b'Coms.Extra'),
        ),
        migrations.AddField(
            model_name='commission',
            name='queue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Coms.Queue'),
        ),
        migrations.AddField(
            model_name='commission',
            name='size',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='Coms.Size'),
        ),
        migrations.AddField(
            model_name='commission',
            name='type',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='Coms.Type'),
        ),
        migrations.AddField(
            model_name='commission',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelOptions(
            name='commission',
            options={'default_permissions': ('add', 'view', 'change')},
        ),
        migrations.AlterModelOptions(
            name='commissionfiles',
            options={'default_permissions': ('add', 'view', 'change')},
        ),
        migrations.AlterModelOptions(
            name='queue',
            options={'default_permissions': ('view',)},
        ),
        migrations.AlterModelOptions(
            name='extra',
            options={'default_permissions': ('view',), 'verbose_name': 'Commission Extra'},
        ),
        migrations.AlterModelOptions(
            name='size',
            options={'default_permissions': ('view',), 'verbose_name': 'Commission Size'},
        ),
        migrations.AlterModelOptions(
            name='type',
            options={'default_permissions': ('view',), 'verbose_name': 'Commission Type'},
        ),
        migrations.AlterModelOptions(
            name='contactmethod',
            options={'default_permissions': ('view',), 'verbose_name': 'Contact Method'},
        ),
        migrations.AlterField(
            model_name='commission',
            name='details_date',
            field=models.DateTimeField(blank=True, verbose_name=b'Details Submitted'),
        ),
        migrations.AlterField(
            model_name='commission',
            name='details_date',
            field=models.DateTimeField(null=True, verbose_name=b'Details Submitted'),
        ),
        migrations.AlterModelOptions(
            name='queue',
            options={'default_permissions': ('view',), 'verbose_name': 'Commission Queue'},
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sites', django.contrib.postgres.fields.jsonb.JSONField(default=list)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='commission',
            name='contacts',
        ),
        migrations.RemoveField(
            model_name='commission',
            name='paypal',
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type',
                 models.IntegerField(choices=[(0, b'Initial'), (1, b'Reply'), (2, b'Status Update')], default=2)),
                ('message', models.TextField(blank=True, default=b'', max_length=10000)),
                ('status_changes', django.contrib.postgres.fields.jsonb.JSONField(default=list)),
                ('commission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Coms.Commission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('date', models.DateTimeField(auto_now_add=True,
                                              default=datetime.datetime(2016, 9, 20, 2, 7, 47, 773448, tzinfo=utc),
                                              verbose_name=b'Sent')),
            ],
            options={
                'default_permissions': ('add', 'view', 'change'),
            },
        ),
        migrations.RemoveField(
            model_name='commissionfiles',
            name='note',
        ),
        migrations.AddField(
            model_name='commissionfiles',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Coms.Message'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='commission',
            name='description',
        ),
        migrations.RunPython(
            create_groups
        ),
    ]
