# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-19 04:17
from __future__ import unicode_literals

import Coms.models
from django.conf import settings
import django.contrib.postgres.fields.jsonb
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name=b'Submitted')),
                ('locked', models.BooleanField(default=False)),
                ('status', models.IntegerField(choices=[(0, b'Waiting'), (1, b'Sketched'), (2, b'Lined'), (3, b'Coloured'), (4, b'Finished'), (5, b'Canceled'), (6, b'Please Revise'), (7, b'Rejected')], default=0)),
                ('paid', models.IntegerField(choices=[(0, b'Not Yet Requested'), (1, b'Invoiced'), (2, b'Paid'), (3, b'Refunded')], default=0)),
                ('characters', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('description', models.TextField(blank=True, default=b'', max_length=10000)),
                ('details_date', models.DateTimeField(auto_now=True, verbose_name=b'Details Submitted')),
                ('submitted', models.BooleanField(default=False)),
                ('contacts', django.contrib.postgres.fields.jsonb.JSONField(default=list)),
                ('paypal', models.EmailField(blank=True, default=b'', max_length=254)),
            ],
            options={
                'default_permissions': ('add', 'view'),
            },
        ),
        migrations.CreateModel(
            name='CommissionFiles',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True, default=b'', max_length=1000)),
                ('imgname', models.CharField(max_length=1000)),
                ('img', models.ImageField(upload_to=Coms.models.file_name)),
                ('user_deleted', models.BooleanField(default=False)),
                ('deleted', models.BooleanField(default=False)),
                ('commission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Coms.Commission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ContactMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('message_url', models.URLField(blank=True)),
                ('profile_url', models.URLField(blank=True)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('disabled', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Contact Method',
            },
        ),
        migrations.CreateModel(
            name='Extra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('extra_character_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('disabled', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Commission Extra',
            },
        ),
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name=b'date created')),
                ('max_characters', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('character_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('max_commissions_in_queue', models.IntegerField(default=1)),
                ('max_commissions_per_person', models.IntegerField(default=1)),
                ('expire', models.IntegerField(default=15)),
                ('closed', models.BooleanField(default=False)),
                ('hidden', models.BooleanField(default=False)),
                ('end', models.DateTimeField(blank=True, default=None, null=True)),
                ('start', models.DateTimeField(default=django.utils.timezone.now)),
                ('extras', models.ManyToManyField(blank=True, to='Coms.Extra')),
            ],
            options={
                'verbose_name': 'Commission Queue',
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('extra_character_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('disabled', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Commission Size',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('extra_character_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('disabled', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Commission Type',
            },
        ),
        migrations.AddField(
            model_name='queue',
            name='sizes',
            field=models.ManyToManyField(to='Coms.Size'),
        ),
        migrations.AddField(
            model_name='queue',
            name='types',
            field=models.ManyToManyField(to='Coms.Type'),
        ),
        migrations.AddField(
            model_name='commission',
            name='extras',
            field=models.ManyToManyField(blank=True, to='Coms.Extra'),
        ),
        migrations.AddField(
            model_name='commission',
            name='queue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Coms.Queue'),
        ),
        migrations.AddField(
            model_name='commission',
            name='size',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Coms.Size'),
        ),
        migrations.AddField(
            model_name='commission',
            name='type',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Coms.Type'),
        ),
        migrations.AddField(
            model_name='commission',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
