# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-02 02:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coms', '0001_initial_squashed_0014_merge'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commission',
            options={'default_permissions': ('add',)},
        ),
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name=b'Sent'),
        ),
    ]
