# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-19 04:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Coms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commission',
            options={'default_permissions': ('add', 'view', 'change')},
        ),
    ]
