# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-02 02:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Coms', '0002_auto_20161002_0244'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commission',
            options={'default_permissions': ('add', 'view', 'change')},
        ),
    ]
