# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-03 00:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coms', '0003_auto_20161002_0245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='status_changes',
            field=models.TextField(),
        ),
    ]
