# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-19 05:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Coms', '0003_auto_20160319_0519'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='extra',
            options={'default_permissions': ('view',), 'verbose_name': 'Commission Extra'},
        ),
        migrations.AlterModelOptions(
            name='size',
            options={'default_permissions': ('view',), 'verbose_name': 'Commission Size'},
        ),
        migrations.AlterModelOptions(
            name='type',
            options={'default_permissions': ('view',), 'verbose_name': 'Commission Type'},
        ),
    ]
