# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-17 01:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coms', '0004_auto_20161003_0058'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='token',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
