# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-19 06:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Coms', '0004_auto_20160319_0526'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmethod',
            options={'default_permissions': ('view',), 'verbose_name': 'Contact Method'},
        ),
    ]
