# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-10 02:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Coms', '0007_auto_20160319_2159'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='queue',
            options={'default_permissions': ('view',), 'verbose_name': 'Commission Queue'},
        ),
    ]
