# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-19 23:34
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Coms', '0009_auto_20160919_2308'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(0, b'Initial'), (1, b'Reply'), (3, b'Status Update')], default=2)),
                ('message', models.TextField(blank=True, default=b'', max_length=10000)),
                ('status_changes', django.contrib.postgres.fields.jsonb.JSONField(default=list)),
                ('commission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Coms.Commission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'default_permissions': ('add', 'view', 'change'),
            },
        ),
        migrations.RemoveField(
            model_name='commissionfiles',
            name='note',
        ),
    ]
