# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-19 23:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Coms', '0010_auto_20160919_2334'),
    ]

    operations = [
        migrations.AddField(
            model_name='commissionfiles',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Coms.Message'),
            preserve_default=False,
        ),
    ]
