# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-20 02:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Coms', '0011_commissionfiles_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commission',
            name='description',
        ),
        migrations.AddField(
            model_name='message',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 9, 20, 2, 7, 47, 773448, tzinfo=utc), verbose_name=b'Sent'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='type',
            field=models.IntegerField(choices=[(0, b'Initial'), (1, b'Reply'), (2, b'Status Update')], default=2),
        ),
    ]
